[package]
name = "async-socket"
version = "0.1.0"
publish = false
authors = ["Rob Ede <robjtede@icloud.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.97"

[dependencies]
async-svc = { path = "../svc", version = "0.0.2" }
tokio = { version = "1.13.1", features = ["full"] }
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
tracing = "0.1.30"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
