name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with: { toolchain: nightly }

      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: tests
        run: cargo test --workspace --all-features

  doc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with: { toolchain: nightly }

      - name: doc tests
        run: cargo test --workspace --doc --all-features
